server:
  port: 9001
spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: TRPG-service
  profiles:
    active: dev
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://43.138.44.237:3306/TRPG?characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: halden
      password: 228888
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 43.138.44.237
    port: 6379
    password: 228888

#  rabbitmq:
#    host: 43.138.44.237
#    port: 5672
#    username: admin
#    password: admin
mybatis-plus:
  mapper-locations: mappers/*.xml


on-path: http://localhost:9001/file/


ftp:
  host: 43.138.44.237
  port: 21
  username: halden
  password: 228888