server:
  port: 9001
spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: TRPG-service
  profiles:
    active: dev
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://****:****/TRPG?characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: ****
      password: ****
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: ******
    port: ****
    password: ****

mybatis-plus:
  mapper-locations: mappers/*.xml


on-path: http://localhost:9001/file/
